import * as fs from "fs";
import * as path from "path";
import { pathToFileURL } from "url";
import { calendars } from "../data/calendars";
import { sessionByFormula } from "../utils/sessions";
import type { CalendarEvent } from "../types/CalendarEvent";
import type { RaceSession } from "../types/RaceSession";

function toIso(s?: string, ctx?: string): string {
  if (!s) return "";
  const mFull = s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z?$/);
  const mShort = s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})Z?$/);
  if (mFull) {
    const [, y, mon, d, hh, mm, ss] = mFull;
    return new Date(Date.UTC(+y, +mon - 1, +d, +hh, +mm, +ss)).toISOString();
  }
  if (mShort) {
    const [, y, mon, d, hh, mm] = mShort;
    return new Date(Date.UTC(+y, +mon - 1, +d, +hh, +mm, 0)).toISOString();
  }
  throw new Error(`Unable to parse date "${s}"${ctx ? ` for ${ctx}` : ""}`);
}

function sessionsToTsContent(varName: string, sessions: RaceSession[]): string {
  const header = `// Auto-generated by process-calendars.ts\n// Do not edit by hand.\n\n`;
  const importType = `import type { RaceSession } from "../types/RaceSession";\n\n`;

  const body = `export const ${varName}: RaceSession[] = ${JSON.stringify(sessions, null, 2)};\n`;

  return header + importType + body;
}

async function run(): Promise<void> {
  try {
    for (const cal of calendars) {
      if (!cal.calendarEventsFile) {
        console.warn(`No calendarEventsFile configured for ${cal.name}, skipping.`);
        continue;
      }
      if (!fs.existsSync(cal.calendarEventsFile)) {
        console.warn(`Skipping ${cal.name}: calendar events file not found at ${cal.calendarEventsFile}`);
        continue;
      }
      const varName = `${cal.name.toLowerCase()}CalendarEvents`;
      let mod: any;
      try {
        // Use require so this works under ts-node (CommonJS execution)
        mod = require(path.resolve(cal.calendarEventsFile as string));
      } catch (err) {
        console.error(`Failed to load calendar events file ${cal.calendarEventsFile}:`, err);
        continue;
      }
      const events: CalendarEvent[] = (mod && mod[varName]) || [];

      if (!events || events.length === 0) {
        console.log(`No events in ${cal.calendarEventsFile}`);
      }

      const typesForCal = sessionByFormula(cal.formula) || [];
      if (!typesForCal || typesForCal.length === 0) {
        console.error(`No session types for formula "${cal.formula}" (calendar: ${cal.name}), skipping.`);
        continue;
      }

      const sessions: RaceSession[] = [];
      for (const props of events) {
        const session: RaceSession = {
          startDateTime: props["DTSTART"] ? toIso(props["DTSTART"], props["SUMMARY"] || props["UID"]) : undefined,
          endDatetime: props["DTEND"] ? toIso(props["DTEND"], props["SUMMARY"] || props["UID"]) : undefined,
        };

        if (props["GEO"]) {
          const [latS, lonS] = (props["GEO"] || "").split(";");
          const lat = parseFloat(latS as string);
          const lon = parseFloat(lonS as string);
          if (!Number.isNaN(lat) && !Number.isNaN(lon)) session.coords = { lat, lon };
        }

        // enrich
        session.formulaSlug = cal.formula;
        let matched: string | undefined = undefined;
        const cats = props["CATEGORIES"] ? props["CATEGORIES"].split(",").map((c) => c.trim().toLowerCase()) : [];
        if (cats.length > 0) {
          for (const t of typesForCal) {
            if (!t || !t.calCategory) continue;
            if (cats.includes(t.calCategory.toLowerCase())) {
              matched = t.slug;
              break;
            }
          }
        }
        if (matched) session.sessionTypeSlug = matched;

        sessions.push(session);
      }

      const outPath = cal.raceSessionsFile;
      const outDir = path.dirname(outPath);
      if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

      const outVar = `${cal.name.toLowerCase()}Sessions`;
      const content = sessionsToTsContent(outVar, sessions);
      fs.writeFileSync(outPath, content, "utf8");
      console.log(`Wrote ${outPath} (${sessions.length} sessions)`);
      console.log("");
    }
  } catch (err) {
    console.error("process-calendars failed:", err);
    process.exit(1);
  }
}

run();
